# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""
(metadata, coarse_latent) -> obs

step 1. coarse latent -> fine latent (lower res)

    y[p x factor + i, d] = sum_c W_icd z_cp
    0 <= i < factor
    d = c / factor

step 2. mlp w/ metadata + embed_id -> scalar

"""

import torch
import torch.distributed.nn.functional as df
import earth2grid.healpix
import math
from healda.models.healpix_layers import Subdomain


class HieararchicalGraphConvDown(torch.nn.Module):
    """
    Graph convolution layer for hierarchically structured data.

    Scatters features from parent nodes to child nodes.
    This is simpler than a typical GCN because the edge structure is defined by
    parent_id, creating edges from each child to its parent.

    Args:
        in_features: Input feature dimension
        out_features: Output feature dimension
    """

    def __init__(self, in_features: int, out_features: int):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.weight = torch.nn.Linear(in_features, out_features)

    def forward(
        self,
        child_features: torch.Tensor,
        parent_id: torch.Tensor,
        parent_features: torch.Tensor,
    ) -> torch.Tensor:
        """
        Aggregate features from children to parents.

        Args:
            child_features: [num_nodes, in_features] - Features for all nodes
            parent_id: [num_nodes] - Parent index for each node (0 <= parent_id < num_parents)
            parent_features: [num_parents, out_features] - Parent features

        Returns:
            [num_parents, out_features] - Aggregated features for parents
        """
        x_parent = self.weight(parent_features)  # [num_nodes, out_features]
        x_child = self.weight(child_features)
        x = (x_child + x_parent[parent_id]) / math.sqrt(2)
        return x


class ObsDecoder(torch.nn.Module):
    """
    Decoder for generating observations from latent representations.

    This decoder performs two main steps:
    1. Coarse latent -> fine latent (lower resolution)
    2. MLP with metadata + embed_id -> scalar observation values

    The decoder uses sparse patch decoding similar to ViT, where observations
    are generated by gathering latent features at specific HEALPix pixel locations.

    Args:
        latent_dim: Dimension of the input latent representation
        metadata_dim: Dimension of the metadata features
        max_embed_id: Maximum embedding ID for lookup table
        hpx_fine_level: HEALPix level for fine resolution grid
        embed_dim: Dimension of the embedding vectors
        obs_dim: Dimension of the output observation values
        hidden_dim: Hidden dimension for the MLP layers
        use_layer_norm: Whether to use layer normalization
        dropout: Dropout probability
    """

    def __init__(
        self,
        latent_dim: int,
        metadata_dim: int,
        max_embed_id: int,
        hpx_fine_level: int,
        hpx_in_level: int,
        obs_dim: int = 1,
        hidden_dim: int = 64,
        use_layer_norm: bool = True,
        dropout: float = 0.0,
    ):
        super().__init__()
        if hpx_fine_level < hpx_in_level:
            raise ValueError(f"{hpx_fine_level} must be >= {hpx_in_level}")

        self.latent_dim = latent_dim
        self.metadata_dim = metadata_dim
        self.obs_dim = obs_dim
        self.hpx_fine_level = hpx_fine_level
        self.hpx_in_level = hpx_in_level

        # Setup HEALPix grid for fine level
        self.fine_grid = earth2grid.healpix.Grid(
            level=hpx_fine_level, pixel_order=earth2grid.healpix.NEST
        )
        self.npix_fine = 12 * 4**hpx_fine_level
        self.factor = 4 ** (hpx_fine_level - hpx_in_level)
        self.hidden_dim = hidden_dim

        # Step 1: Coarse latent -> fine latent (lower resolution)
        # This could be implemented as a simple linear projection or more complex upsampling
        self.latent_proj = torch.nn.Linear(latent_dim, hidden_dim * self.factor)

        # Embedding lookup for embed_ids
        self.embed_platform = torch.nn.Embedding(max_embed_id, hidden_dim)
        self.embed_channel = torch.nn.Embedding(max_embed_id, hidden_dim)
        self.embed_obs_type = torch.nn.Embedding(max_embed_id, hidden_dim)

        self.metadata_proj = torch.nn.Linear(metadata_dim, hidden_dim)

        # Step 2: MLP with metadata + embed_id -> scalar
        # Input: hidden_dim (from latent) + metadata_dim + embed_dim
        input_dim = hidden_dim

        layers = []
        layers.append(torch.nn.Linear(input_dim, hidden_dim))

        if use_layer_norm:
            layers.append(torch.nn.LayerNorm(hidden_dim))

        layers.append(torch.nn.SiLU())

        if dropout > 0:
            layers.append(torch.nn.Dropout(dropout))

        layers.append(torch.nn.Linear(hidden_dim, obs_dim))

        self.mlp = torch.nn.Sequential(*layers)
        self._group = None

    def set_parallel_group(self, group: torch.distributed.ProcessGroup):
        """the parallel group to use. all_gathers the shards"""
        self._group = group

    def forward(
        self,
        latent: torch.Tensor,
        batch_idx: torch.Tensor,
        metadata: torch.Tensor,
        pix: torch.Tensor,
        platform,
        channel,
        obs_type,
        hpx_level: int,
        subdomain: Subdomain | None = None,
    ) -> torch.Tensor:
        """
        Forward pass of the observation decoder.

        Args:
            latent: (b, t, x, c) - coarse latent representation, hpxpad order for x
            batch_idx: (nobs,) - batch index for each observation
            metadata: (nobs, c1) - metadata features for each observation
            pix: (nobs) - pix NEST convention
            embed_ids: (nobs) - embedding IDs for lookup
            hpx_level: the healpix level of pix


        Returns:
            obs: (nobs, obs_dim) - decoded observation values
        """

        if self._group is not None:
            x_dim = 2
            latents = df.all_gather(latent, self._group)
            latent = torch.cat(latents, dim=x_dim)

        if hpx_level < self.hpx_fine_level:
            raise ValueError(f"{hpx_level} must be >= {self.hpx_fine_level}")

        if subdomain is not None:
            raise NotImplementedError()

        b, t, x, c = latent.shape
        nobs, _ = metadata.shape

        pix_coarsened = pix // int(4.0 ** (hpx_level - self.hpx_in_level))
        local_pix = pix // int(4.0 ** (hpx_level - self.hpx_fine_level))
        local_pix = local_pix % self.factor
        pix_parent = earth2grid.healpix.nest2xy(
            2**self.hpx_in_level,
            pix_coarsened,
            pixel_order=earth2grid.healpix.HEALPIX_PAD_XY,
        )

        # Step 1: Coarse latent -> fine latent
        fine_latent = self.latent_proj(latent).reshape(
            b * t * x * self.factor, self.hidden_dim
        )

        # Gather latent features at observation pixel locations
        index = batch_idx * x * self.factor + pix_parent * self.factor + local_pix
        fine_latent_gathered = fine_latent[index]

        # Step 2: MLP with metadata + embed_id -> scalar
        # Concatenate fine latent, metadata, and embeddings
        mlp_input = (
            self.metadata_proj(metadata)
            + fine_latent_gathered
            + self.embed_channel(channel)
            + self.embed_obs_type(obs_type)
            + self.embed_platform(platform)
        ) / math.sqrt(5)
        obs = self.mlp(mlp_input)  # (nobs, obs_dim)
        return obs
